### ISSUE TITLE
Incorrect highlighting for nested arrays

### ISSUE THREAD

**Issue by FooSoft** [cespare/vim-toml#9]
The code below incorrectly highlights the nested array as a table:

```toml
foo = [
    ["a", "b", "c"]
]
```

In order for the highlighting to work properly on nested arrays, a trailing comma must be added as seen below:

```toml
foo = [
    ["a", "b", "c"],
]
```
